---
- name: Checking workspace
  assert:
    that:
      - project_workspace is defined
      - (project_workspace | length) > 0
      - project_workspace != 'default'
    msg: >-
      Variable 'project_workspace' must be defined, non-empty and not equal to 'default'

- name: Checking terraform action
  assert:
    that:
      - tf_action is defined
      - tf_action in ['apply', 'destroy']
    msg: >-
      'tf_action' must be defined and one of ['apply', 'destroy']


- name: APPLY - Ensure Directories
  delegate_to: localhost
  become: no
  run_once: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    recurse: yes
  loop:
    - "{{ project_workspace_tf_modules_dir }}"
    - "{{ project_workspace_group_vars_dir }}"
    - "{{ project_secrets_directory }}"
  when: tf_action == 'apply'