---
collections:
  - name: community.crypto
  - name: community.general
    version: 4.5.0
  - name: community.mysql

roles:
  - src: https://github.com/MakarenaLabs/ansible-role-wordpress.git
    version: master
    scm: git
  - src: https://github.com/fauust/ansible-role-mariadb.git
    version: main
    scm: git

